### ISSUE TITLE
Invalid JS syntax in Washing your code: avoid conditions

### ISSUE THREAD

**Issue by vkrol** [sapegin/blog.sapegin.me#25]
![Снимок экрана 2019-08-19 в 9 16 44](https://user-images.githubusercontent.com/153412/63243117-41eac800-c262-11e9-9f7a-4c3a86f78ff6.png)
![Снимок экрана 2019-08-19 в 9 17 05](https://user-images.githubusercontent.com/153412/63243119-42835e80-c262-11e9-9c6d-816f0cd81c2d.png)

**Comment by sapegin** [comment]
Thanks, that's a bug in my typography plugin — will try to fix it ;-/
