### ISSUE TITLE
Confusing code font

### ISSUE THREAD

**Issue by vkrol** [sapegin/blog.sapegin.me#26]
The font used in code listings is confusing. 
Compare `render,` and `fireEvent ,`:
![F70F6309-E722-4EF4-B80C-D0C998F9B567](https://user-images.githubusercontent.com/153412/63301159-8b7af780-c2e2-11e9-9dc8-f669111d5cdd.jpeg)

**Comment by sapegin** [comment]
Looks fine for me: 

![image](https://user-images.githubusercontent.com/70067/63326204-074d6200-c32c-11e9-9128-4ff47d021461.png)

What browser and OS are you using?

P. S. It definitely shouldn't use default monospace font though :rage1:

**Comment by vkrol** [comment]
Very strange :) It is Safari on iPad (iOS 12.4).

**Comment by sapegin** [comment]
Interesting 🍆  I'll try to fix the font stack and ask you to look again ;-)

**Comment by vkrol** [comment]
OK! Thanks.

**Comment by sapegin** [comment]
I can see it in desktop Safari too, changing the font doesn't help:

![Screenshot 2019-08-20 at 9 53 22 am](https://user-images.githubusercontent.com/70067/63328452-7a58d780-c330-11e9-8bf1-114d4a0965d6.png)

**Comment by sapegin** [comment]
I think I've fixed it! Thanks for reporting!

**Comment by vkrol** [comment]
Yes, it's fixed now. No problem.
